modLoader="javafml"
loaderVersion="[37,)"
license="The MIT License (MIT)"
issueTrackerURL="https://github.com/Tomson124/SimplyJetpacks2/issues"

[[mods]]
modId="simplyjetpacks"
version="${file.jarVersion}"
displayName="Simply Jetpacks 2"
updateJSONURL="https://raw.githubusercontent.com/Tomson124/SimplyJetpacks2/1.17/updates/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/simply-jetpacks-2"
logoFile="logo.png"
credits="cybercat5555"
authors="StormedPanda, Tomson124"
description='''
Simply Jetpacks 2

Jetpacks and Fluxpacks powered by Forge Energy!

Previous Author: tonius11
'''

[[dependencies.simplyjetpacks]]
modId="forge"
mandatory=true
versionRange="[37,)"
ordering="NONE"
side="BOTH"

[[dependencies.simplyjetpacks]]
modId="minecraft"
mandatory=true
versionRange="[1.17.1,1.18)"
ordering="NONE"
side="BOTH"
